### ISSUE TITLE
Official IRC channel for project discussion

### ISSUE THREAD

**Issue by runfalk** [pedrocr/rawloader#3]
I usualy idle freenode and thought it would be a good idea to have an IRC channel for implementation discussion so I registered `#rawloader`. Some of the issues with my pull request (#2) might have been avoided if I discussed them with you beforehand.

**Comment by pedrocr** [comment]
I already created #chimper on irc.mozilla.org. Would that work?

**Comment by runfalk** [comment]
That works too. It may even make more sense since Mozilla has all the support channels for Rust.

**Comment by pedrocr** [comment]
I've updated the README to point to #chimper on irc.mozilla.org
