### ISSUE TITLE
Advice/Documentation for final brightness

### ISSUE THREAD

**Issue by phip1611** [pedrocr/rawloader#40]
Maybe I'm missing something but I do not understand yet how I can determine the final/real brightness.

For example, if a camera only a bit-depth of 12 then 0x0fff is max brightness. If a camera uses 14 bit then 0x3ff is the max brightness of a pixel. How can I find out the final/real brightness with what's given right now by the library?

**Comment by pedrocr** [comment]
See the `whitelevels` and `blacklevels` fields. They give you the minimum and maximum values per channel. You can also use `imagepipe` to process the image for you or to just see the ops and their sequence to get inspiration on how to do your own processing:

https://github.com/pedrocr/imagepipe

**Comment by pedrocr** [comment]
This is all from experience from working on other raw pipelines and then several resources online. Bruce Lindbloom's website for example has a bunch of useful resources on color conversions:

http://www.brucelindbloom.com/index.html
