### ISSUE TITLE
Demosaicing Bits in example from README.md

### ISSUE THREAD

**Issue by schmauder** [pedrocr/rawloader#41]
in the example of the README.md file i had to change line

let pixlow  = (pix&0x0f) as u8;

into

let pixlow  = (pix&0xff) as u8;

else i got dramatic posterization. i don't know whether this is a typo or has to do with the bit depth of my camera (14-Bit, arw format, Sony IlCE-7SM2).

**Comment by pedrocr** [comment]
Thanks! That was just wrong. It's even doing it in the low pixel and just throwing away the top 4 bits. By the way, if you're looking to do processing maybe `imagepipe` would be helpful:

https://github.com/pedrocr/imagepipe

Either to use as is or to just look up as inspiration on how to design a pipeline for your use case.
